# Generated by Django 3.2.9 on 2021-11-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0003_auto_20211115_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
