# Generated by Django 3.2.9 on 2021-11-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0004_auto_20211116_0130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('pass_number', 'pass_serial')},
        ),
    ]
