# Generated by Django 3.2.9 on 2021-11-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0005_alter_client_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pass_and_serial',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
    ]
