# Generated by Django 3.2.9 on 2021-11-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0007_alter_client_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pass_serial',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='groupclient',
            name='client',
            field=models.ManyToManyField(blank=True, to='djangoApp.Client'),
        ),
    ]
