# Generated by Django 3.2.9 on 2021-11-24 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0008_auto_20211119_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('contact_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Номер телефона введен в неверном формате! Пример: +79261234567, 89261234567, 79261234567, 123-45-67 и т.п.', regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')])),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
